id: PC778BCFD
initial_creation_type: input
source_metadata:
  title: Amitābha and Sukhāvatī Series
  language: nl
  description: 'Texts and practices related to Buddha Amitābha and his pure-land,
    the blissful western paradise of Sukhāvatī (bde ba can), including prayers of
    aspiration to be reborn in Sukhāvatī (bde smon):'
  volume:
    964244bab0134e7faac1df8875825459:
      title: Aspiration for Rebirth in Sukhāvatī
      parent: Aspiration Prayers (bde smon)
    400cd7bfb2c74f568905c54c565a3fda:
      title: Prayer to Buddha Amitābha
      parent: Aspiration Prayers (bde smon)
    5af54a9560944dd48616a4bba4f6721d:
      title: A Sukhāvatī Prayer and Aspiration
      parent: Aspiration Prayers (bde smon)
    b637f24c720e4837b1b08bdb6831f119:
      title: Brief Sukhāvatī Aspiration
      parent: Aspiration Prayers (bde smon)
    579ad9980e6b43c6849673d058843764:
      title: Aspiration for the Land of Great Bliss
      parent: Aspiration Prayers (bde smon)
    5c7597cfbcc14f32807a1994f65bc443:
      title: Aspiration to Be Reborn in the Realm of Sukhāvatī
      parent: Aspiration Prayers (bde smon)
    0a6177db55484782990a3f8151f4b9c6:
      title: Prayer of Aspiration Towards Sukhāvatī
      parent: Aspiration Prayers (bde smon)
    d85b2e0c33ea4c89b5cae3ebe429fc02:
      title: Sukhāvatī Aspiration
      parent: Aspiration Prayers (bde smon)
    599f7ac564d34b1cb8a7f7102188b4e6:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Aspiration Prayers (bde smon)
    d2b768e398f24e50b09ddba736b74491:
      title: Prayer to Behold Amitābha in Dreams
      parent: Aspiration Prayers (bde smon)
    5340a4675d9645bf86255067db042f05:
      title: Verso Inscription on an Image of the Pure Land of Great Bliss
      parent: Inscriptions
    fe05e3250b4144c8b1ca57cc6de2b7bb:
      title: Brief Amitābha Sleeping Practice
      parent: Meditation
    e6a19dec46e546b2a520010a65a98f9a:
      title: Meditation on Amitābha
      parent: Meditation
    49974b8e3f98485b8f6b64d8fbd07364:
      title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
        Light'
      parent: Sādhanas
created_at: '2022-03-01T02:41:42.987013'
last_modified_at: '2022-03-01T02:41:42.987015'
